FROM ollama/ollama:0.1.29

WORKDIR /opt/ollama

COPY Modelfile /opt/ollama/Modelfile
COPY scripts/ollama-sidecar-init.sh /usr/local/bin/ollama-sidecar-init.sh
RUN chmod +x /usr/local/bin/ollama-sidecar-init.sh

EXPOSE 11434

VOLUME ["/root/.ollama"]

CMD ["/usr/local/bin/ollama-sidecar-init.sh"]
